---
title: "Longitudinal Shoe Study"
output: github_document
---

## Study Description

A longitudinal study of 160 shoes. Shoes were Nike Winflo 4 or Adidas Seeley, and were worn for approximately 6 months, with data collected initially and during 4 check-in periods. 

### Collection Method Documentation

#### Initial Longitudinal Study

The [baseline collection procedures](Collection_Procedures/Documentation/Methods-Techniques-Shoe.pdf) were used in the collection of initial data about the unworn shoes and the study participants as well as during the study. The baseline procedure documents the collection procedures; a separate document describes [changes made to these procedures during the study](Collection_Procedures/Documentation/Procedure.pdf) to improve image quality and reduce equipment malfunctions. 

In addition, single-procedure files are provided for each collection method:

- [Tekscan Mat Scanner](Collection_Procedures/Documentation/Mat-Scanner-Procedure.pdf)
- [2d Digital Scanner (EverOS Everspry)](Collection_Procedures/Documentation/2d-Procedure.pdf)
- [Digital Camera](Collection_Procedures/Documentation/Camera-Tripod-Procedure.pdf)
- [Film/Powder Prints](Collection_Procedures/Documentation/Film-Powder-Print.pdf)
- [Paper Print/Vinyl Prints](Collection_Procedures/Documentation/Paper-Powder-Print.pdf)
    - [Vinyl Print photos](Collection_Procedures/Documentation/Vinyl-Photo-Procedure.pdf)
    - [Scanner Procedure - paper and film prints](Collection_Procedures/Documentation/Epson-Bed-Scanner.pdf)
- [3d Digital Scanner (Stationary)](Collection_Procedures/Documentation/EinScan-Pro+-3D-Scanner-Procedure-Phase-2.pdf) - for the EinScan Pro+ 3D Scanner with a turntable

#### Realistic Prints Expansion

At the conclusion of the longitudinal study, we decided to create prints similar to those which may be found at a crime scene with some of the worn shoes. 

- [Dental Stone Casting](Collection_Procedures/Documentation/Casting-Procedure.pdf)
- [Shoe Impressions in Dust](Collection_Procedures/Documentation/Shoe-Impressions-in-Dust-Photography-and-Lifting-Procedure.pdf)
